---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: microservice-dev
  namespace: dev
  #annotations:
    #fluxcd.io/automated: "true"
    #filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: microservice-dev
  chart:
    git: git@github.com:mifonpe/microservice-demo
    path: ./
    ref: develop
  values:
    java:
      options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    zipkin: 
      enabled:  false
      url: zipkin.zipkin.svc.cluster.local
    catalogue:
    enabled: true
    image: weaveworksdemos/catalogue
    version: 0.3.5
    database: 
        image: weaveworksdemos/catalogue-db
        version: 0.3.0
        persistence:
            enabled: true
            size: 1Gi
            storageclass: default 
    frontend:
      replicas: 1
    loadtest:
      replicas: 2
      enabled: false
