---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: microservice-dev
  namespace: dev
spec:
  releaseName: microservice-dev
  chart:
    git: git@github.com:mifonpe/microservice-demo
    path: ./
    ref: develop
  values:
    environment: dev
    zipkin: 
      enabled:  false
    carts:
      enabled: false
    orders:
      enabled: false
    catalogue:
      enabled: true
    queuemaster:
      enabled: false
    rabbitmq:
      enabled: false
    sessiondb:
      enabled: false
    shipping:
      enabled: false
    payment:
      enabled: false
    loadtest:
      replicas: 2
      enabled: false


