---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: microservice-int
  namespace: int
  #annotations:
    #fluxcd.io/automated: "true"
    #filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: microservice-int
  chart:
    git: git@github.com:mifonpe/microservice-demo
    path: ./
    ref: int
  values:
    java:
      options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    zipkin: 
      enabled:  false
      url: zipkin.zipkin.svc.cluster.local
    frontend:
      replicas: 1
    loadtest:
      replicas: 2
      enabled: false
