---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: microservice-int
  namespace: int
spec:
  releaseName: microservice-int
  chart:
    git: git@github.com:mifonpe/microservice-demo
    path: ./
    ref: int
  values:
    environment: int
    zipkin: 
      enabled:  false
    carts:
      enabled: false
    orders:
      enabled: false
    catalogue:
      enabled: false
    user:
      enabled: false
    queuemaster:
      enabled: false
    rabbitmq:
      enabled: false
    sessiondb:
      enabled: false
    shipping:
      enabled: false
    payment:
      enabled: false
    loadtest:
      replicas: 2
      enabled: false
    frontend:
      enabled: true
    
