# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - develop
    paths:
      - '/charts*'
  pull_request:
    branches: 
      - master
      - develop
    paths:
      - '/charts*'
jobs:

  build:

    runs-on: self-hosted


    steps:

    - uses: actions/checkout@v2

    - name: Helm lint for Helm Charts
      env:
        - HELM_URL=https://storage.googleapis.com/kubernetes-helm
        - HELM_TAR=helm-v2.4.1-linux-amd64.tar.gz
      run: |
        wget -q ${HELM_URL}/${HELM_TAR}
        tar xzfv ${HELM_TAR}
        PATH=`pwd`/linux-amd64/:$PATH
        helm init --client-only
        for chart in `ls ./charts`; do
          helm lint ./charts/${chart}
          if [ $? != 0 ]; then
            exit 1
          fi
        done
