---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: microservice-prod
  namespace: prod
spec:
  releaseName: microservice-prod
  chart:
    git: git@github.com:mifonpe/microservice-demo
    path: ./
    ref: master
  values:
    environment: prod
    zipkin: 
      enabled:  false
    carts:
      enabled: true
    orders:
      enabled: true
    catalogue:
      enabled: true
    user:
      enabled: true
    queuemaster:
      enabled: true
    rabbitmq:
      enabled: true
    sessiondb:
      enabled: true
    shipping:
      enabled: true
    payment:
      enabled: true
    loadtest:
      replicas: 2
      enabled: false
    frontend:
      enabled: true
