# This is a basic workflow to help you get started with Actions

name: helmlint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - develop
    paths:
      - 'charts/**'
  pull_request:
    branches: 
      - master
      - develop
    paths:
      - 'charts/**'
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Helm lint for Helm Charts
      run: |
        for chart in `ls ./charts`; do
          helm lint ./charts/${chart}
          if [ $? != 0 ]; then
            echo "${chart} didn't pass the lint check!"
            exit 1
          fi
        done
